#!/bin/sh
### BEGIN INIT INFO
# Provides:          {{ name }}
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Manages app {{ name }}
### END INIT INFO

export RAILS_ENV='production'
export NODE_ENV='production'

SCRIPT='echo "run app command here"'
RUNAS=root

PIDFILE=/var/run/{{ name }}.pid
LOGFILE=/var/log/{{ name }}.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service {{ name }} already running' >&2
    return 1
  fi
  echo 'Starting service {{ name }}' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service {{ name }} started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service {{ name }} not running' >&2
    return 1
  fi
  echo 'Stopping service {{ name }}' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service {{ name }} stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall service {{ name }}? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f flashlight remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac