#!/usr/bin/env bash
#
# Install
#
# This installs some of the common dependencies needed (or at least desired)
# 

if test $(uname -s) = 'Darwin'
then
  $HOME/.dotfiles/osx/set-defaults.sh 2>&1
fi

# Check for Homebrew
if test $(which brew)
then
  # Upgrade homebrew
  brew update

  # Install ALL THE THINGS!!
  brew install autoconf autoenv automake brew-cask chromedriver ctags ec2-api-tools freetype gdbm git imagemagick jpeg libevent libgpg-error libksba libpng libtool libyaml node openssl ossp-uuid pcre pkg-config postgresql pstree qt rbenv readline redis ruby-build s3cmd ssh-copy-id the_silver_searcher tmux tree watch wget xz zsh

elif test $(which apt-get)
  
  # Upgrade apt, add node repo, update cache
  apt-get -y upgrade
  apt-add-repository -y ppa:chris-lea/node.js
  apt-get -y update

  # Install ALL THE THINGS!!
  apt-get install build-essential git-core autoconf automake curl wget nodejs imagemagick jpeg libevent-dev libgpg-error-dev libksba-dev libpng12-dev libtool libyaml-dev openssl libossp-uuid-dev pcre libpcre3-dev postgresql rbenv readline-common redis-server s3cmd tmux tree wget xz-utils zsh

else
  echo "  x Couldn't find homebrew or apt-get"
  exit
fi

# Node packages
if test $(which npm)
then
  npm install -g bower grunt grunt-cli slap 2>&1
else
  echo "  x Node not installed - wtf?"
  exit
fi

# Ruby version
if test -z $(ruby -v | grep 2.1.1)
then
  if rbenv install 2.1.1 2>&1
  then
    rbenv global 2.1.1
  else
    echo "  x Ruby 2.1.1 failed to install"
  fi
fi

# Gems
if test $(which gem)
then
  gem install bundler 2>&1
else
  echo "  x Rubygems not installed - wtf?"
  exit
fi

exit 0